version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-hello-world"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wh6zbny2z2lr"
s3_prefix = "sam-hello-world"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
